const colorConfig = {
  statusBar: '#039dfc',
  home: {
    container: '#039dfc',
    textStyle: '#fff',
    button: '#1c313a',
    buttonText: '#ffffff',
  },
  signin: {
    container: '#ffffff',
    signupText: '#ffffff',
    signupButton: '#ffffff',
    button: '#068944',
    shadowColor: '#ffffff',
    buttonText: '#ffffff',
    buttonLoginWith: '#039dfc',
    buttonTextLoginWith: '#1c313a',
    textLoginWith: '#1c313a',
    errorText: '#039dfc',
  },
  signup: {
    container: '#039dfc',
    signupText: '#039dfc',
    signupButton: '#ffffff',
    button: '#068944',
    shadowColor: '#039dfc',
    buttonText: '#ffffff',
    errorText: '#ffffff',
  },
  auth: {
    container: '#039dfc',
    signupText: '#039dfc',
    signupButton: '#ffffff',
    button: '#068944',
    shadowColor: '#039dfc',
    buttonText: '#ffffff',
    errorText: '#ffffff',
  },
  splash: {
    container: '#FFF',
    ViewStyle: '#fff',
  },
  pageIndex: {
    activeTintColor: '#039dfc',
    inactiveTintColor: '#CBCBCB',
    grayColor: '#A2A2A2',
    backgroundColor: '#FFFFFF',
    listBorder: '#FAA21C',
  },
  store: {
    defaultColor: '#039dfc',
    storesItem: '#FFFFFF',
    scrollView: '#FFFBF4',
    storesTitle: '#039dfc',
    border: '#31393d',
    colorSuccess: '#44c769',
    colorError: '#c7420e',
    textWhite: 'white',
    title: '#333231',
    transparentColor: 'rgba(3, 157, 252, 0.8)',
  },
};

export default colorConfig;
