name: Build Android Demo

on:
  workflow_dispatch:
    inputs:
      company_name:
        description: 'Company Name'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.21.3'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386

      - name: Install dependencies
        run: yarn install

      - name: Setup project
        run: yarn move-${{ inputs.company_name }}-mac

      - name: Build APK
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > $GITHUB_WORKSPACE/android/app/release-key.keystore
          yarn apk-release-demo

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ inputs.company_name }} - APK(s) Demo generated
          path: android/app/build/outputs/apk/demo/release/