name: Deploy Android Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386

      - name: Set Gradle properties
        run: sed -i "s|^org.gradle.java.home=.*|org.gradle.java.home=${JAVA_HOME}|" $GITHUB_WORKSPACE/gradle.properties

      - name: Install dependencies
        run: yarn install

      - name: Set default project setup
        run: yarn move-funtoast-mac

      - name: Check if FEF project
        if: github.event_name == 'pull_request' && startsWith(github.event.pull_request.title, 'FUNTOAST') && github.event.pull_request.head.ref == 'main'
        run: yarn move-fareastflora-mac

      - name: Build APK
        run: yarn android-demo-rel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-demo-release.apk
          path: android/app/build/outputs/apk/demo/release/